src/main/java/com/mycompany/jv27_spring_project_final/entities/AccountEntity.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jv27_spring_project_final.entities;

import com.mycompany.jv27_spring_project_final.Ultil.StringUltil;
import com.mycompany.jv27_spring_project_final.entities.enums.ActiveStatus;
import com.mycompany.jv27_spring_project_final.entities.enums.Role;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

/**
 *
 * @author taing
 */
@Entity
@Table(name = "account")
public class AccountEntity implements Serializable{
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    @Column(name = "user_name", nullable = false,unique = true)
    private String username;
    
    @Column(name = "password", nullable = false)
    private String password;
    
    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.MERGE)
    @JoinTable(name = "account_role_relation",
            joinColumns = @JoinColumn(name = "account_id",referencedColumnName = "id"),
            inverseJoinColumns = @JoinColumn(name = "role_id",referencedColumnName = "id"))
    private List<AccountRoleEntity> accountRoles;

    @Column(unique = true,nullable = false)
    private String email;
    @DateTimeFormat(pattern = "yyyy-mm-dd")
    @Temporal(TemporalType.DATE)
    private Date birthday;
    @Column(name = "full_name")
    private String fullName;
    private String address;
    private String phone;
    @Enumerated(EnumType.STRING)
    private ActiveStatus status = ActiveStatus.INACTIVE;
    
   @OneToMany(mappedBy = "account", fetch = FetchType.LAZY)
   private List<FavoriteEntity> favorites;
   
   @OneToMany(mappedBy = "account", fetch = FetchType.LAZY)
   private List<CommentEntity> comments;
   
   @OneToMany(mappedBy = "account", fetch = FetchType.LAZY)
   private List<OrderEntity> orders;
    
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<AccountRoleEntity> getAccountRoles() {
        return accountRoles;
    }

    public void setAccountRoles(List<AccountRoleEntity> accountRoles) {
        this.accountRoles = accountRoles;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public ActiveStatus getStatus() {
        return status;
    }

    public void setStatus(ActiveStatus status) {
        this.status = status;
    }

   

    public List<FavoriteEntity> getFavorites() {
        return favorites;
    }

    public void setFavorites(List<FavoriteEntity> favorites) {
        this.favorites = favorites;
    }

    public List<CommentEntity> getComments() {
        return comments;
    }

    public void setComments(List<CommentEntity> comments) {
        this.comments = comments;
    }   

    public AccountEntity() {
    }

    public List<OrderEntity> getOrders() {
        return orders;
    }

    public void setOrders(List<OrderEntity> orders) {
        this.orders = orders;
    }
    
    
    
    public String getRoleString(){
        for(AccountRoleEntity role : accountRoles){
            if(role.getRoles() == Role.ROLE_ADMIN){
                return "ROLE_ADMIN";
            }
        }
        for(AccountRoleEntity role : accountRoles){
            if(role.getRoles()== Role.ROLE_SELLER){
                return "ROLE_SELLER";
            }
        }
        return "ROLE_USER";
    }
    public String getBirthdayFormat(){
        if(birthday==null){
            return "";
        }
        return StringUltil.fromDateToUS(birthday);
    }
    
}

src/main/java/com/mycompany/jv27_spring_project_final/controller/AccountController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jv27_spring_project_final.controller;

import com.mycompany.jv27_spring_project_final.Ultil.AccountUltil;
import com.mycompany.jv27_spring_project_final.entities.AccountEntity;
import com.mycompany.jv27_spring_project_final.entities.AccountRoleEntity;
import com.mycompany.jv27_spring_project_final.entities.OrderEntity;
import com.mycompany.jv27_spring_project_final.entities.VerifyEmailEntity;
import com.mycompany.jv27_spring_project_final.entities.enums.ActiveStatus;
import com.mycompany.jv27_spring_project_final.entities.enums.Role;
import com.mycompany.jv27_spring_project_final.service.AccountRoleService;
import com.mycompany.jv27_spring_project_final.service.AccountService;
import com.mycompany.jv27_spring_project_final.service.OrderService;
import com.mycompany.jv27_spring_project_final.service.VerifyEmailService;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.regex.Pattern;
import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.mail.MailException;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

/**
 *
 * @author taing
 */
@Controller
public class AccountController {

    @Autowired
    private OrderService orderService;

    @Autowired
    private AccountService accountService;

    @Autowired
    private AccountRoleService accountRoleService;

    @Autowired
    private JavaMailSender mailSender;

    @Autowired
    private VerifyEmailService verifyEmailService;

    @RequestMapping("/account")
    public String viewAccount(Model model,
            @RequestParam(value = "action", required = false) String action,
            @RequestParam(value = "page", required = false) Integer page) {
        if (action == null || action.isEmpty()) {
            AccountEntity account = AccountUltil.getAccount();
            model.addAttribute("account", account);
            return "account/profile";
        } else if (action.equals("myorder")) {
            if (page == null || page <= 0) {
                page = 1;
            }
            AccountEntity account = AccountUltil.getAccount();
            Page<OrderEntity> ordersPage = orderService.getOrdersByAccountId(account.getId(), page);
            model.addAttribute("orders", ordersPage.getContent());
            model.addAttribute("page", ordersPage.getTotalPages());
            return "account/myorder";
        } else if (action.equals("changepassword")) {
            return "account/changepassword";
        } else {
            AccountEntity account = AccountUltil.getAccount();
            model.addAttribute("account", account);
            return "account/profile";
        }
    }

    @RequestMapping(value = "/register", method = RequestMethod.GET)
    public String viewRegister(Model model) {
        return "register";
    }

    @RequestMapping("/login")
    public String loginPage() {
        return "login";
    }

    @RequestMapping(value = "/register-account", method = RequestMethod.POST)
    public String registerAccount(Model model, @ModelAttribute(value = "account") AccountEntity account, @ModelAttribute(value = "password1") String password1, @ModelAttribute(value = "password2") String password2) {
        if (!Pattern.matches("^[a-zA-Z0-9_]+$", account.getUsername())) {
            model.addAttribute("messageError", "The username contains illegal characters.");
            return "register";
        }
        if (password1.length() < 5) {
            model.addAttribute("messageError", "Password must be greater than or equal to 5 characters");
            return "register";
        }
        if (!password1.equals(password2)) {
            model.addAttribute("messageError", "Password is not the same, please check again");
            return "register";
        }
        AccountEntity checkUsername = accountService.getAccountByUsername(account.getUsername());
        if (checkUsername != null) {
            model.addAttribute("messageError", "This username already exists");
            return "register";
        }
        AccountEntity checkEmail = accountService.getAccountByEmail(account.getEmail());
        if (checkEmail != null) {
            model.addAttribute("messageError", "This email address already exists");
            return "register";
        }
        account.setPassword(password2);
        List<AccountRoleEntity> accountRoleEntitys = new ArrayList<>();
        accountRoleEntitys.add(accountRoleService.getAccountRolesByRole(Role.ROLE_USER));
        account.setAccountRoles(accountRoleEntitys);
        AccountEntity accountSaved = accountService.saveAccount(account);
        if (accountSaved != null && accountSaved.getId() > 0) {
            String verifyCode = UUID.randomUUID().toString();
            VerifyEmailEntity verify = new VerifyEmailEntity();
            verify.setEmail(accountSaved.getEmail());
            verify.setCode(verifyCode);
            VerifyEmailEntity verifyCodeSaved = verifyEmailService.save(verify);
            if (verifyCodeSaved != null & verifyCodeSaved.getId() > 0) {
                try {
                    MimeMessage mimeMessage = mailSender.createMimeMessage();
                    MimeMessageHelper helper = new MimeMessageHelper(mimeMessage, false, "utf-8");
                    String htmlMsg = "<p>To activate your account, please verify your email address by clicking on the link below:</p><a href=\"http://localhost:8080/JV27_Spring_Project_Final/verify?email=" + accountSaved.getEmail() + "&code=" + verifyCode + "\">Verify now</a>";
                    mimeMessage.setContent(htmlMsg, "text/html");
                    helper.setTo(accountSaved.getEmail());
                    helper.setSubject("Activate your account");
                    mailSender.send(mimeMessage);
                } catch (MailException | MessagingException m) {
                    model.addAttribute("messageError", "Successful account registration but email confirmation failed<br/>" + m);
                    return "register";
                }
                model.addAttribute("messageSuccess", "Successful account registration, please confirm the link has been sent to the email");
                return "register-success";
            } else {
                model.addAttribute("messageError", "Successful account registration but can't create email verify code");
            }

        } else {
            model.addAttribute("messageError", "Unable to register your account");
        }

        return "register";
    }

    @RequestMapping(value = "/update-account", method = RequestMethod.POST)
    public String updateAccount(Model model, @ModelAttribute(value = "account") AccountEntity acc) {
        AccountEntity account = AccountUltil.getAccount();
        account.setFullName(acc.getFullName());
        account.setAddress(acc.getAddress());
        account.setBirthday(acc.getBirthday());
        account.setPhone(acc.getPhone());
        AccountEntity checkEmail = accountService.getAccountByEmail(acc.getEmail());
        if (checkEmail == null) {
            account.setEmail(acc.getEmail());
        }
        accountService.saveAccount(account);
        model.addAttribute("messageSuccess", "Successfully updated account profile");
        model.addAttribute("account", account);
        return "account/profile";
    }

    @RequestMapping(value = "/update-password", method = RequestMethod.POST)
    public String updatePassword(Model model, 
            @ModelAttribute(value = "password") String password, 
            @ModelAttribute(value = "newpassword1") String newpassword1, 
            @ModelAttribute(value = "newpassword2") String newpassword2) {
        if (newpassword1.equals(newpassword2)) {
            AccountEntity account = AccountUltil.getAccount();
            if (account.getPassword().equals(password)) {
                account.setPassword(newpassword1);
                accountService.saveAccount(account);
                model.addAttribute("messageSuccess", "Successfully updated password");
            } else {
                model.addAttribute("messageError", "Password incorrect");
            }
        } else {
            model.addAttribute("messageError", "The new password is not the same");
        }
        return "account/changepassword";
    }

    @RequestMapping(value = "/verify")
    public String verify(Model model,
            @RequestParam(value = "email") String email,
            @RequestParam(value = "code") String code) {
        VerifyEmailEntity verify = verifyEmailService.getVerify(email, code);
        if (verify == null) {
            model.addAttribute("messageError", "Verify code or email invalid");
        } else {
            AccountEntity account = accountService.getAccountByEmail(email);
            account.setStatus(ActiveStatus.ACTIVE);
            accountService.saveAccount(account);
            verifyEmailService.delete(verify);
            model.addAttribute("messageSuccess", "Email validation successful");
        }
        return "verifyStatus";
    }
}

src/main/webapp/WEB-INF/jsp/account/changepassword.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="f" %>
<!DOCTYPE html>
<html lang="en">
    <!-- head -->
    <head>
        <title>Change your password</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="Little Closet template">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/styles/bootstrap-4.1.2/bootstrap.min.css"></c:url>">
        <link href="<c:url value="/resources/plugins/font-awesome-4.7.0/css/font-awesome.min.css"></c:url>" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/plugins/OwlCarousel2-2.2.1/owl.carousel.css"></c:url>">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/plugins/OwlCarousel2-2.2.1/owl.theme.default.css"></c:url>">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/plugins/OwlCarousel2-2.2.1/animate.css"></c:url>">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/styles/main_styles.css"></c:url>">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/styles/responsive.css"></c:url>">
        </head>
        <body>
            <!-- Mobile Menu -->
        <jsp:include page="../include/mobile-menu.jsp"/>

            <div class="super_container">

                <!-- Header -->
            <jsp:include page="../include/header.jsp"/>

                <div class="super_container_inner">
                    <div class="super_overlay"></div>		
                    <div class="container">
                        <div class="row" style="margin-top: 100px">
                            <div class="col-lg-6 offset-lg-3">
                                <div class="section_title text-center">Change Password</div>
                            </div>
                        </div>
                        <div class="row page_nav_row">
                            <div class="col">
                                <div class="page_nav">
                                    <ul class="d-flex flex-row align-items-start justify-content-center">
                                    <c:import url="../include/account-menu.jsp"></c:import>                                         
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="row mainmain">
                            <div class="col-xs-12 col-sm-12">
                                <p style="font-size: 150%;color: red;text-align: center">${messageError}</p>
                            <p style="font-size: 150%;color: blue;text-align: center">${messageSuccess}</p>
                            <f:form action="${pageContext.request.getContextPath()}/update-password" method="post" class="form-horizontal">
                                <div class="table-responsive">
                                    <table class="table table-bordered">
                                        <tr>
                                            <th>Current password <span style="color: red">(*)</span></th>
                                            <td><input type="password" name="password" class="form-control" required/></td>
                                        </tr>
                                        <tr>
                                            <th>New password <span style="color: red">(*)</span></th>
                                            <td><input type="password" name="newpassword1" class="form-control" pattern=".{5,50}" title="Limit 5-50 characters" required/></td>
                                        </tr>
                                        <tr>
                                            <th>Confirm password <span style="color: red">(*)</span></th>
                                            <td><input type="password" name="newpassword2" class="form-control" pattern=".{5,50}" title="Limit 5-50 characters" required/></td>
                                        </tr>                                        
                                    </table>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-12 col-xs-12" style="text-align: center">
                                        <button type="submit" class="btn btn-primary">Update</button>                                      
                                    </div>
                                </div>
                            </f:form>
                        </div>
                    </div>
                </div>
                <!-- profile -->



            </div>
        </div>

        <!-- Footer -->
        <jsp:include page="../include/footer.jsp"/>

            <!-- script -->
            <script src="<c:url value="/resources/js/jquery-3.2.1.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/styles/bootstrap-4.1.2/popper.js"></c:url>"></script>
        <script src="<c:url value="/resources/styles/bootstrap-4.1.2/bootstrap.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/greensock/TweenMax.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/greensock/TimelineMax.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/scrollmagic/ScrollMagic.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/greensock/animation.gsap.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/greensock/ScrollToPlugin.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/easing/easing.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/progressbar/progressbar.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/parallax-js-master/parallax.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/js/custom.js"></c:url>"></script>
    </body>
</html>

src/main/webapp/WEB-INF/jsp/account/profile.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="f" %>
<!DOCTYPE html>
<html lang="en">
    <!-- head -->
    <head>
        <title>My Profile</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="Little Closet template">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/styles/bootstrap-4.1.2/bootstrap.min.css"></c:url>">
        <link href="<c:url value="/resources/plugins/font-awesome-4.7.0/css/font-awesome.min.css"></c:url>" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/plugins/OwlCarousel2-2.2.1/owl.carousel.css"></c:url>">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/plugins/OwlCarousel2-2.2.1/owl.theme.default.css"></c:url>">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/plugins/OwlCarousel2-2.2.1/animate.css"></c:url>">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/styles/main_styles.css"></c:url>">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/styles/responsive.css"></c:url>">
        </head>
        <body>
            <!-- Mobile Menu -->
        <jsp:include page="../include/mobile-menu.jsp"/>

            <div class="super_container">

                <!-- Header -->
            <jsp:include page="../include/header.jsp"/>

                <div class="super_container_inner">
                    <div class="super_overlay"></div>		
                    <div class="container">
                        <div class="row" style="margin-top: 100px">
                                <div class="col-lg-6 offset-lg-3">
                                    <div class="section_title text-center">My Profile</div>
                                </div>
                            </div>
                        <div class="row page_nav_row">
                            <div class="col">
                                <div class="page_nav">
                                    <ul class="d-flex flex-row align-items-start justify-content-center">
                                        <jsp:include page="../include/account-menu.jsp"/>                                       
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="row mainmain">
                            <div class="col-xs-12 col-sm-12">
                                <p style="font-size: 150%;color: red;text-align: center">${messageError}</p>
                            <p style="font-size: 150%;color: blue;text-align: center">${messageSuccess}</p>
                            <f:form action="${pageContext.request.getContextPath()}/update-account" method="post" modelAttribute="account" class="form-horizontal">
                                <div class="table-responsive">
                                    <table class="table table-bordered">
                                        <tr>
                                            <th>Full name <span style="color: red">(*)</span></th>
                                            <td><input type="text" name="fullName" value="${account.fullName}" class="form-control" pattern="[A-Za-z ]{3,50}" title="Only letters and space are allowed, length 3-50" required/></td>
                                        </tr>
                                        <tr>
                                            <th>Email <span style="color: red">(*)</span></th>
                                            <td><input type="email" name="email" value="${account.email}" class="form-control" required/></td>
                                        </tr>
                                        <tr>
                                            <th>Phone</th>
                                            <td><input type="text" name="phone" value="${account.phone}" pattern="[0-9]{10,11}" title="Only numbers are allowed, length 10-11" class="form-control"/></td>
                                        </tr>
                                        <tr>
                                            <th>Birthday</th>
                                            <td><input type="date" name="birthday" value="${account.birthdayFormat}" class="form-control"/></td>
                                        </tr>
                                        <tr>
                                            <th>Address</th>
                                            <td><input type="text" name="address" value="${account.address}" class="form-control"/></td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-12 col-xs-12" style="text-align: center">
                                        <button type="submit" class="btn btn-primary">Update</button>                                      
                                    </div>
                                </div>
                            </f:form>
                        </div>
                    </div>
                </div>
                <!-- profile -->



            </div>
        </div>

        <!-- Footer -->
        <jsp:include page="../include/footer.jsp"/>

            <!-- script -->
            <script src="<c:url value="/resources/js/jquery-3.2.1.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/styles/bootstrap-4.1.2/popper.js"></c:url>"></script>
        <script src="<c:url value="/resources/styles/bootstrap-4.1.2/bootstrap.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/greensock/TweenMax.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/greensock/TimelineMax.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/scrollmagic/ScrollMagic.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/greensock/animation.gsap.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/greensock/ScrollToPlugin.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/easing/easing.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/progressbar/progressbar.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/parallax-js-master/parallax.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/js/custom.js"></c:url>"></script>
    </body>
</html>