src/main/java/com/mycompany/jv27_spring_project_final/entities/OrderDetailEntity.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jv27_spring_project_final.entities;

import com.mycompany.jv27_spring_project_final.Ultil.NumberUltil;
import com.mycompany.jv27_spring_project_final.Ultil.StringUltil;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 *
 * @author taing
 */
@Entity
@Table(name = "order_detail")
public class OrderDetailEntity implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(nullable = false)
    private int quantity;

    @ManyToOne
    @JoinColumn(name = "size_id",nullable = false)
    private SizeEntity size;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "product_id",nullable = false)
    private ProductEntity product;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id",nullable = false)
    private OrderEntity order;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "promotion_id")
    private PromotionEntity promotion;

    public OrderDetailEntity() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public ProductEntity getProduct() {
        return product;
    }

    public void setProduct(ProductEntity product) {
        this.product = product;
    }

    public OrderEntity getOrder() {
        return order;
    }

    public void setOrder(OrderEntity order) {
        this.order = order;
    }

    public SizeEntity getSize() {
        return size;
    }

    public void setSize(SizeEntity size) {
        this.size = size;
    }

    public PromotionEntity getPromotion() {
        return promotion;
    }

    public void setPromotion(PromotionEntity promotion) {
        this.promotion = promotion;
    }

    public double getTotal() {
        if (promotion != null && promotion.getDiscount() > 0) {
            return NumberUltil.roundDoubleMoney(this.product.getPrice() * this.quantity * (100 - this.promotion.getDiscount()) / 100, 2);
        }
        return NumberUltil.roundDoubleMoney(this.product.getPrice() * this.quantity, 2);
    }

    public double getTotalDiscount() {
        if (promotion != null && promotion.getDiscount() > 0) {
            return NumberUltil.roundDoubleMoney(this.product.getPrice() * this.quantity * this.promotion.getDiscount() / 100, 2);
        }
        return 0;
    }
}

src/main/java/com/mycompany/jv27_spring_project_final/entities/ProductEntity.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jv27_spring_project_final.entities;

import com.mycompany.jv27_spring_project_final.entities.enums.ActiveStatus;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

/**
 *
 * @author taing
 */
@Entity
@Table(name = "product")
public class ProductEntity implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(nullable = false)
    private String name;
    @Column(nullable = false)
    private double price;
    private String description;
    @Column(nullable = false, unique = true)
    private String code;
    private String brand;
    
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Temporal(TemporalType.DATE)
    @Column(name = "date",nullable = false)
    private Date date;
    
    @Enumerated(EnumType.STRING)
    private ActiveStatus status = ActiveStatus.ACTIVE;

    @ManyToOne
    @JoinColumn(name = "category_id",nullable = false)
    private CategoryEntity category;

    @ManyToOne
    @JoinColumn(name = "color_id")
    private ColorEntity color;

    @ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinTable(name = "product_size_relation",
            joinColumns = @JoinColumn(name = "product_id", referencedColumnName = "id"),
            inverseJoinColumns = @JoinColumn(name = "size_id", referencedColumnName = "id"))
    private List<SizeEntity> sizes;

    @ManyToMany(mappedBy = "products")    
    private List<PromotionEntity> promotions;

    @OneToMany(mappedBy = "product", fetch = FetchType.LAZY)
    private List<FavoriteEntity> favorites;

    @OneToMany(mappedBy = "product", fetch = FetchType.LAZY)
    private List<CommentEntity> comments;

    @OneToMany(mappedBy = "product", fetch = FetchType.EAGER, cascade = CascadeType.REMOVE)
    private List<ImagesEntity> images;

    public ProductEntity() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public ActiveStatus getStatus() {
        return status;
    }

    public void setStatus(ActiveStatus status) {
        this.status = status;
    }
    
    public String getStatusString(){
        return status.name();
    }

    public CategoryEntity getCategory() {
        return category;
    }

    public void setCategory(CategoryEntity category) {
        this.category = category;
    }

    public ColorEntity getColor() {
        return color;
    }

    public void setColor(ColorEntity color) {
        this.color = color;
    }

    public List<SizeEntity> getSizes() {
        return sizes;
    }

    public void setSizes(List<SizeEntity> sizes) {
        this.sizes = sizes;
    }

    public List<PromotionEntity> getPromotions() {
        return promotions;
    }

    public void setPromotions(List<PromotionEntity> promotions) {
        this.promotions = promotions;
    }

    public List<FavoriteEntity> getFavorites() {
        return favorites;
    }

    public void setFavorites(List<FavoriteEntity> favorites) {
        this.favorites = favorites;
    }

    public List<CommentEntity> getComments() {
        return comments;
    }

    public void setComments(List<CommentEntity> comments) {
        this.comments = comments;
    }

    public List<ImagesEntity> getImages() {
        return images;
    }

    public void setImages(List<ImagesEntity> images) {
        this.images = images;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    

    public int getTotalFavorite() {
        return this.favorites.size();
    }  
    
}

src/main/java/com/mycompany/jv27_spring_project_final/controller/HomeController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jv27_spring_project_final.controller;

import com.mycompany.jv27_spring_project_final.Ultil.AccountUltil;
import com.mycompany.jv27_spring_project_final.entities.AccountEntity;
import com.mycompany.jv27_spring_project_final.entities.CommentEntity;
import com.mycompany.jv27_spring_project_final.entities.FavoriteEntity;
import com.mycompany.jv27_spring_project_final.entities.ProductEntity;
import com.mycompany.jv27_spring_project_final.entities.SizeEntity;
import com.mycompany.jv27_spring_project_final.service.CategoryService;
import com.mycompany.jv27_spring_project_final.service.CommentService;
import com.mycompany.jv27_spring_project_final.service.FavoriteService;
import com.mycompany.jv27_spring_project_final.service.ProductService;
import com.mycompany.jv27_spring_project_final.service.PromotionService;
import com.mycompany.jv27_spring_project_final.service.SizeService;
import java.util.ArrayList;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

/**
 *
 * @author taing
 */
@Controller
public class HomeController {

    @Autowired
    private ProductService productService;

    @Autowired
    private SizeService sizeService;

    @Autowired
    private CommentService commentService;

    @Autowired
    private FavoriteService favoriteService;

    @Autowired
    private PromotionService promotionService;
    
     @Autowired
     private CategoryService categoryService;

    @RequestMapping(value = {"/", "/home"}, method = RequestMethod.GET)
    public String homePage(Model model,
            @RequestParam(value = "page", required = false) Integer page) {        
        if (page == null || page <= 0) {
            page = 1;
        }
        Page<ProductEntity> productsPage = productService.getProductsActive(page);
        List<ProductEntity> productsList = productsPage.getContent();
        List<ProductEntity> products = new ArrayList<>();
        for (int i = 0; i < productsList.size(); i++) {
            ProductEntity product = productsList.get(i);
            List<FavoriteEntity> favs = favoriteService.getFavoritesByProductId(product.getId());
            product.setFavorites(favs);
            products.add(product);
        }
        model.addAttribute("page", productsPage.getTotalPages());
        model.addAttribute("products", products);
        return "home";
    }

    @RequestMapping(value = "/category", method = RequestMethod.GET)
    public String categoryPageLimit(Model model, 
            @RequestParam("id") int id, 
            @RequestParam(value = "page", required = false) Integer page,
            @RequestParam(value = "sort", required = false) String sort) {
        if (page == null || page <= 0) {
            page = 1;
        }
        Page<ProductEntity> productsPage = null;
        if(sort==null || sort.isEmpty()){
            productsPage = productService.getProductByCategoryId(id,page,"none");
        }else{
            productsPage = productService.getProductByCategoryId(id,page,sort);
        }
        
        List<ProductEntity> productsList = productsPage.getContent();
        List<ProductEntity> products = new ArrayList<>();
        for (int i = 0; i < productsList.size(); i++) {
            ProductEntity product = productsList.get(i);
            List<FavoriteEntity> favs = favoriteService.getFavoritesByProductId(product.getId());
            product.setFavorites(favs);
            products.add(product);
        }
        model.addAttribute("category", categoryService.getCategoryById(id));
        model.addAttribute("page", productsPage.getTotalPages());
        model.addAttribute("products", products);
        return "category";
    }

    @RequestMapping(value = "/product", method = RequestMethod.GET)
    public String productPage(Model model, @RequestParam("id") int id) {
        ProductEntity product = productService.getProductById(id);
        List<SizeEntity> sizes = sizeService.getSizeByProductId(id);
        model.addAttribute("product", product);
        model.addAttribute("sizes", sizes);
        List<CommentEntity> comments = commentService.getCommentsByProductId(id);
        model.addAttribute("comments", comments);
        model.addAttribute("favorites", favoriteService.countFavoriteByProductId(id));
        AccountEntity account = AccountUltil.getAccount();
        if (account != null) {
            FavoriteEntity fav = favoriteService.getFavotiteByAccountIDAndProductID(account.getId(), id);
            if (fav != null) {
                model.addAttribute("favorited", true);
            } else {
                model.addAttribute("favorited", false);
            }
        } else {
            model.addAttribute("favorited", false);
        }
        model.addAttribute("promotions", promotionService.getPromotionsByProductId(id));
        return "product";
    }

}

src/main/webapp/WEB-INF/jsp/category.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>${category.name}</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="Little Closet template">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/styles/bootstrap-4.1.2/bootstrap.min.css"></c:url>">
        <link href="<c:url value="/resources/plugins/font-awesome-4.7.0/css/font-awesome.min.css"></c:url>" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/plugins/OwlCarousel2-2.2.1/owl.carousel.css"></c:url>">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/plugins/OwlCarousel2-2.2.1/owl.theme.default.css"></c:url>">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/plugins/OwlCarousel2-2.2.1/animate.css"></c:url>">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/styles/category.css"></c:url>">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/styles/category_responsive.css"></c:url>">
        </head>
        <body>

            <!-- Mobile Menu -->
        <jsp:include page="./include/mobile-menu.jsp"/>

        <div class="super_container">

            <!-- Header -->	
            <jsp:include page="./include/header.jsp"/>

            <div class="super_container_inner">
                <div class="super_overlay"></div>                   

                <!-- Products -->

                <div class="products" style="margin-top: 10px">
                    <div class="container">
                        <div class="row" style="margin-top: 130px; margin-bottom: 15px;">
                            <div class="col-xl-12 col-md-12">                                
                                <div class="dropdown float-right">
                                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Sort by
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="<c:url value="/category?id=${param.id}&sort=Latest"/>">Latest</a>
                                        <a class="dropdown-item" href="<c:url value="/category?id=${param.id}&sort=Oldest"/>">Oldest</a>
                                        <a class="dropdown-item" href="<c:url value="/category?id=${param.id}&sort=HightoLow"/>">Price: High to Low</a>
                                        <a class="dropdown-item" href="<c:url value="/category?id=${param.id}&sort=LowtoHigh"/>">Price: Low to High</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row products_row products_container grid">

                            <c:forEach var="product" items="${products}">
                                <!-- Product -->
                                <div class="col-xl-4 col-md-6 grid-item new">
                                    <div class="product">
                                        <div class="product_image"><a href="<c:url value="/product?id=${product.id}"></c:url>"><img src="${product.images[0].url}" alt=""></div>
                                                    <div class="product_content">
                                                        <div class="product_info d-flex flex-row align-items-start justify-content-start">
                                                            <div>
                                                                <div>
                                                                    <div class="product_name"><a href="<c:url value="/product?id=${product.id}"></c:url>">${product.name}</a></div>
                                                                <div class="product_category">In <a href="<c:url value="/category?id=${product.category.id}&page=1"></c:url>">${product.category.name}</a></div>
                                                                </div>
                                                            </div>
                                                            <div class="ml-auto text-right">
                                                                <div class="rating_r rating_r_4 home_item_rating">${product.totalFavorite} favorite</div>
                                                            <div class="product_price text-right">$${product.price}</div>
                                                        </div>
                                                    </div>                                           
                                                </div>
                                        </div>
                                    </div>
                                </c:forEach>                               

                            </div>
                            <div class="row page_nav_row">
                                <div class="col">
                                    <div class="page_nav">
                                        <ul class="d-flex flex-row align-items-start justify-content-center">                                            
                                            <c:forEach begin="1" end="${page}" varStatus="status">
                                                <c:choose>
                                                    <c:when test="${param.page==null && status.index==1}">
                                                        <li class="active"><a href="<c:url value="/category?id=${param.id}&page=${status.index}&sort=${param.sort}"/>">${status.index}</a></li>
                                                        </c:when>
                                                        <c:when test="${param.page==null && status.index!=1}">
                                                        <li><a href="<c:url value="/category?id=${param.id}&page=${status.index}&sort=${param.sort}"/>">${status.index}</a></li>
                                                        </c:when>
                                                        <c:when test="${param.page!=null && param.page==status.index}">
                                                        <li class="active"><a href="<c:url value="/category?id=${param.id}&page=${status.index}&sort=${param.sort}"/>">${status.index}</a></li>
                                                        </c:when>                                                   
                                                        <c:otherwise>
                                                        <li><a href="<c:url value="/category?id=${param.id}&page=${status.index}&sort=${param.sort}"/>">${status.index}</a></li>
                                                        </c:otherwise>
                                                    </c:choose>                                          
                                                </c:forEach>                                                  
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Footer -->
                    <jsp:include page="./include/footer.jsp"/>

                </div>

            </div>

            <script src="<c:url value="/resources/js/jquery-3.2.1.min.js"></c:url>"></script>
            <script src="<c:url value="/resources/styles/bootstrap-4.1.2/popper.js"></c:url>"></script>
            <script src="<c:url value="/resources/styles/bootstrap-4.1.2/bootstrap.min.js"></c:url>"></script>
            <script src="<c:url value="/resources/plugins/greensock/TweenMax.min.js"></c:url>"></script>
            <script src="<c:url value="/resources/plugins/greensock/TimelineMax.min.js"></c:url>"></script>
            <script src="<c:url value="/resources/plugins/scrollmagic/ScrollMagic.min.js"></c:url>"></script>
            <script src="<c:url value="/resources/plugins/greensock/animation.gsap.min.js"></c:url>"></script>
            <script src="<c:url value="/resources/plugins/greensock/ScrollToPlugin.min.js"></c:url>"></script>
            <script src="<c:url value="/resources/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></c:url>"></script>
            <script src="<c:url value="/resources/plugins/easing/easing.js"></c:url>"></script>
            <script src="<c:url value="/resources/plugins/progressbar/progressbar.min.js"></c:url>"></script>
            <script src="<c:url value="/resources/plugins/parallax-js-master/parallax.min.js"></c:url>"></script>
            <script src="<c:url value="/resources/plugins/Isotope/isotope.pkgd.min.js"></c:url>"></script>
            <script src="<c:url value="/resources/plugins/Isotope/fitcolumns.js"></c:url>"></script>
            <script src="<c:url value="/resources/js/category.js"></c:url>"></script>
            <script src="<c:url value="/resources/js/product-script-custom.js"></c:url>"></script>  
    </body>
</html>

src/main/webapp/WEB-INF/jsp/checkout.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="f" %>
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Checkout</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="Little Closet template">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/styles/bootstrap-4.1.2/bootstrap.min.css"></c:url>">
        <link href="<c:url value="/resources/plugins/font-awesome-4.7.0/css/font-awesome.min.css"></c:url>" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/styles/checkout.css"></c:url>">
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/styles/checkout_responsive.css"></c:url>">
        </head>
        <body>

            <!-- Mobile Menu -->
        <jsp:include page="./include/mobile-menu.jsp"/>

        <div class="super_container">

            <!-- Header -->
            <jsp:include page="./include/header.jsp"/>

            <div class="super_container_inner">
                <div class="super_overlay"></div>

                <!-- Home -->

                <div class="home">
                    <div class="home_container d-flex flex-column align-items-center justify-content-end">
                        <div class="home_content text-center">
                            <div class="home_title">Checkout</div>
                            <div class="breadcrumbs d-flex flex-column align-items-center justify-content-center">
                                <ul class="d-flex flex-row align-items-start justify-content-start text-center">
                                    <li><a href="#">Home</a></li>
                                    <li>Checkout</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Checkout -->
                <f:form action="${pageContext.request.getContextPath()}/checkout-process" method="post" modelAttribute="shipping" id="checkout_form" class="checkout_form">
                    <div class="checkout">
                        <div class="container">
                            <div class="row">

                                <!-- Billing -->
                                <div class="col-lg-6">
                                    <div class="billing">
                                        <div class="checkout_title">Shipping</div>
                                        <div class="checkout_form_container">

                                            <div>
                                                <input type="text" id="checkout_name" name="fullName" class="checkout_input" value="${account.fullName}" placeholder="Full Name" pattern="[A-Za-z ]{3,50}" title="Only letters and space are allowed, length 3-50" required>
                                            </div>								

                                            <div>
                                                <!-- Address -->
                                                <input type="text" id="checkout_address" name="address" class="checkout_input" value="${account.address}" placeholder="Address Line" required>

                                            </div>									

                                            <div>
                                                <!-- Phone no -->
                                                <input type="text" id="checkout_phone" name="phone" class="checkout_input" value="${account.phone}" placeholder="Phone No." pattern="[0-9]{10,11}" title="Only numbers are allowed, length 10-11" required>
                                            </div>
                                            <div>
                                                <!-- Email -->
                                                <input type="email" id="checkout_email" name="email" class="checkout_input" value="${account.email}" placeholder="Email" required>
                                            </div>                                           

                                        </div>
                                    </div>
                                </div>

                                <!-- Cart Total -->
                                <div class="col-lg-6 cart_col">
                                    <div class="cart_total">
                                        <div class="cart_extra_content cart_extra_total">
                                            <div class="checkout_title">Cart Total</div>
                                            <ul class="cart_extra_total_list">
                                                <li class="d-flex flex-row align-items-center justify-content-start">
                                                    <div class="cart_extra_total_title">Subtotal</div>
                                                    <div class="cart_extra_total_value ml-auto">$${order.total}</div>
                                                </li>
                                                <li class="d-flex flex-row align-items-center justify-content-start">
                                                    <div class="cart_extra_total_title">Shipping</div>
                                                    <div class="cart_extra_total_value ml-auto">Free</div>
                                                </li>
                                                <li class="d-flex flex-row align-items-center justify-content-start">
                                                    <div class="cart_extra_total_title">Total</div>
                                                    <div class="cart_extra_total_value ml-auto">$${order.total}</div>
                                                </li>
                                            </ul>

                                            <div class="cart_text">
                                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra tempor so dales. Phasellus sagittis auctor gravida. Integ er bibendum sodales arcu id te mpus. Ut consectetur lacus.</p>
                                            </div>
                                            <button class="checkout_button trans_200" type="submit"><span>place order</span></button>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </f:form>
                <!-- Footer -->
                <jsp:include page="./include/footer.jsp"/>

            </div>

        </div>
        <script>
            function placeOrder() {
                $('#checkout_form').submit();
            }

        </script>
        <script src="<c:url value="/resources/js/jquery-3.2.1.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/styles/bootstrap-4.1.2/popper.js"></c:url>"></script>
        <script src="<c:url value="/resources/styles/bootstrap-4.1.2/bootstrap.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/greensock/TweenMax.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/greensock/TimelineMax.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/scrollmagic/ScrollMagic.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/greensock/animation.gsap.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/greensock/ScrollToPlugin.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/easing/easing.js"></c:url>"></script>
        <script src="<c:url value="/resources/plugins/parallax-js-master/parallax.min.js"></c:url>"></script>
        <script src="<c:url value="/resources/js/checkout.js"></c:url>"></script>
    </body>
</html>